run:
  train: true         # Training ausführen?
  gui: true           # Zeichen-GUI nach dem Training/Laden starten
  viz: false          # Erste-Layer-Gewichte als Tiles anzeigen

# Trainiere neu oder lade Gewichte
weights:
  save_path: ./artifacts/mnist_relu_best.npz
  load_if_exists: false   # true = existierende Gewichte laden statt zu trainieren

seed: 42

model:
  input_dim: 784
  # ENTWEDER ein Layer:
  #hidden_dims: [64]
  # ODER zwei Layer (Beispiel):
  hidden_dims: [128, 64]
  output_dim: 10

# Daten (MNIST via OpenML beim ersten Lauf)
data:
  dataset: mnist
  test_size: 10000
  random_state: 42
  dataset_limit: null     # z.B. 8000 für schnelle Demos, sonst null für ganzes MNIST

# Trainingsblock — Trainer auswählen
train:
  trainer: sgd            # sgd | ga | hybrid
  sgd:
    epochs: 10
    batch_size: 128
    lr: 0.05
  ga:
    pop_size: 20
    generations: 6
    sigma: 0.05
    elite_frac: 0.1
    tournament_k: 3
    fitness_batch: 2000

# Visualisierung
viz:
  max_units: 64

# GUI
gui:
  cell_px: 12
